services:
  - type: web
    name: fewminutespaper-frontend
    env: static
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: client/build
    envVars:
      - key: NODE_VERSION
        value: 18

  - type: web
    name: fewminutespaper-backend
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
